Merge documentation of installing scala-cli on MacOs and MacOs/M1
VirtusLab/scala-cli pull request #1507
Opened 2022-10-29 06:36 UTC by wleczny

2022-11-02 07:05 UTC, lwronski requested changes
I think it's too early to merge, for M1 we don't support nix.

2022-11-02 07:59 UTC, wleczny commented
> I think it's too early to merge, for M1 we don't support nix.

Since every other method is already supporting M1, I would suggest just to add information to nix installation, that it doesn't support M1.

2022-11-02 11:25 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +If you are using M1, run following commands:
```suggestion
When installing Scala CLI on an Apple M1 Mac, run the following commands:
```

2022-11-02 11:25 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +If you are using different architecture than M1, run following commands:
```suggestion
When installing Scala CLI on a non-M1 Mac, run the following commands:
```

2022-11-02 11:25 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +Once downloaded, right-click on downloaded file from Finder and then choose "Open".
```suggestion
Once downloaded, right-click on the downloaded file from Finder and then choose "Open".
```

2022-11-02 11:25 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +Please note that M1 is not supported.
```suggestion
:::info
Please note that M1 is not yet supported with this method.
:::
```

2022-11-02 11:25 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +Scala CLI can be installed with [Nix](https://nixos.org) with:
```suggestion
Scala CLI can be installed via [Nix](https://nixos.org) with:
```

2022-11-02 14:21 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +For Mac with **arm64** architecture, run the following commands:
```suggestion
For a Mac with the **arm64** architecture run the following commands:
```

2022-11-02 14:21 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +For Mac with **x86_64** architecture, run the following commands:
```suggestion
Otherwise, for a Mac with non-**arm64** architecture (pre-M1) run the following commands:
```

2022-11-02 14:21 UTC, Gedochao commented on website/docs/_advanced_install.mdx
> +Please note that arm64 architecture is not yet supported with this method.
```suggestion
Please note that the `arm64` architecture is not yet supported with this method.
```

2022-11-03 07:44 UTC, Gedochao approved these changes

2022-11-03 12:44 UTC, lwronski approved these changes

2022-11-07 09:34 UTC, merged