Cli args in scripts
VirtusLab/scala-cli pull request #178
Opened 2021-10-01 14:57 UTC by tpasternak

2021-10-06 13:58 UTC, tpasternak commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +      // TODO: It's probably impossible to handle `--main-class print`, because we put main method in the other
@alexarchambault @lwronski I couldn't find any way to fix it. This means the scripts users will have to pass `--main-class <somethnig>_sc`, or we will have to add `_sc` suffix silently in options engine

2021-10-06 15:10 UTC, alexarchambault reviewed
I didn't look closely at `MainClassRunner` yet… I'll get back to it a bit later.

2021-10-06 15:10 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/Build.scala
> +        !inputs.sourceFiles().exists(_.isInstanceOf[Inputs.ScriptBase])
Let's not use `isInstanceOf` (if ever the type returned by `sourceFile` changes, we'll get no compiler error here). Better use a match:
```scala
        !inputs.sourceFiles().exists {
          case _: Inputs.ScriptBase => true
          case _ => false
        }
```

2021-10-06 15:10 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/Inputs.scala
> +  sealed trait ScriptBase
`AnyScript` instead of `ScriptBase`? (like the existing `AnyScalaFile`)

2021-10-06 15:10 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/errors/ScalaNativeCompatibilityError.scala
> +case object ScalaNativeCompatibilityError
Exceptions shouldn't be case classes or case objects. For case objects, this gives them a wrong stack trace. For case classes, this breaks the case class semantics, see the discussion around https://github.com/scalameta/metals/pull/3145#discussion_r712800065.

2021-10-06 15:10 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
> +        os.proc(TestUtil.cli, "main0.sc", "f.sc", "--", "20").call(cwd = root, stdout = os.Pipe)
`stdout = os.Pipe` is the default, no need to specify it.

2021-10-06 15:10 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
> +      val p = os.proc(TestUtil.cli, "f.sc", "--", "16").call(cwd = root, stdout = os.Pipe)
Same as above.

2021-10-06 15:10 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +          stderr = os.Pipe
Same as above.

2021-10-06 15:10 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +            root,
Why a new line?

2021-10-06 15:10 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +      // TODO: It's probably impossible to handle `--main-class print`, because we put main method in the other
`--main-class print_sc` is fine for me. I wish it could have been `print.sc`, with the right back-ticks added for it to work.

2021-10-07 07:58 UTC, romanowski requested changes
Please include documentation or even better a cookbook

2021-10-07 07:58 UTC, romanowski commented on modules/build/src/main/scala/scala/build/errors/ScalaNativeCompatibilityError.scala
> +        |  scala-cli --native -S 2.12 <...> (for *.sc files)
```suggestion
        |  scala-cli --native -S 2.13 <...> (for *.sc files)
```

2021-10-07 08:12 UTC, tpasternak commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +      // TODO: It's probably impossible to handle `--main-class print`, because we put main method in the other
I can do it in a separate PR. The problem is that we don't support special characters in --main-class at all. `scala.sc` class is translated to `scala$u002Esc`, but arg passed to `--main-class` remains unchanged. We would have find the code in scala compiler that is used to transform the name and apply this also here. As a quick hack we can just translate some arbitrary symbols (dot, space etc.)

2021-10-07 08:29 UTC, tpasternak commented on modules/build/src/main/scala/scala/build/errors/ScalaNativeCompatibilityError.scala
> +        |  scala-cli --native -S 2.12 <...> (for *.sc files)
For 2.12 we support only .scala files
For 2.13 both .scala and .sc

Hopefully will be fixed in scala-native 4.1

2021-10-07 12:24 UTC, lwronski commented on website/docs/cookbooks/scripting.md
> +# Develop Scripts in Scala
Maybe, we should merge scripting cookbook with this [one](https://github.com/VirtusLab/scala-cli/blob/master/website/docs/cookbooks/scala-scripts.md).

2021-10-07 15:57 UTC, tpasternak commented on website/docs/cookbooks/scripting.md
> +# Develop Scripts in Scala
Can I do it in a follow-up PR?

2021-10-11 12:03 UTC, romanowski approved these changes

2021-10-11 12:14 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/Inputs.scala
> +  sealed trait AnyScript
NIT Make that extend `Element`, so that we know it's related to it.
```suggestion
  sealed trait AnyScript extends Element
```

2021-10-11 12:14 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/Build.scala
> +    if (options.platform == Platform.Native && !scalaNativeSupported(options, inputs))
This check should be done in `buildOnce` rather than here. Some new options may come up from the sources, and can set or change the platform later.

2021-10-11 12:14 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/Build.scala
> +    options.scalaOptions.scalaVersion match {
Getting the Scala version via `options.scalaParams` would give just a `String`, rather than an `Option[String]`, and should be the way to get the Scala version from `BuildOptions`. We may change the default Scala version to a `2.13` one, and `options.scalaParams` would reflect that.

`options.scalaParams` returns an either, but you can use `either` / `value` to deal with it, like other methods in this file.

2021-10-11 12:14 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/errors/ScalaNativeCompatibilityError.scala
> +      """scala-cli: invalid option: '--native' for scripts is supported only for scala 2.13.*
**For later**: we shouldn't mention command-line options from `BuildException` message. Options are managed from the `cli` module, that the `build` module knows nothing about. And these options might not be available for all commands.

I'd like to add a way in each command to print a specific message if some particular exceptions happen, to suggest options there.

Also, the "name" of the application should be `(new scala.cli.internal.Argv0).get("scala-cli")` rather than just `scala-cli`. The former relies on more idiomatic native stuff. If the `scala-cli` file is renamed to `scala` or `scala-cli-1.0`, its value will be `scala` or `scala-cli-1.0` for example.

We should be be able to handle that if we print specific messages for some exceptions, like I mentioned just above.

2021-10-11 12:14 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/internal/CustomClassCodeWrapper.scala
> -package scala.build.internal
NIT Could this class be removed in a specific commit, doing only that?

2021-10-11 12:14 UTC, alexarchambault commented on modules/build/src/test/scala/scala/build/tests/TestUtil.scala
> +        expected.toSet == generated0.map(_.toString).toSet, {
This doesn't change anything, does it?

2021-10-11 12:14 UTC, alexarchambault commented on modules/cli/src/main/scala/scala/cli/commands/SharedOptions.scala
> -    if (classWrap) Some(CustomCodeClassWrapper)
I think we should remove the `classWrap` option here, and the associated CLI option too if there's one.

2021-10-11 12:14 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
> +  test("interconnection between scripts") {
Why is this in `BspTestDefinitions`? `RunTestDefinitions` would be a better fit for this.

2021-10-11 12:14 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
> +      fileName.stripSuffix(".sc") + "_sc" + ext
We shouldn't add a `_sc` to the default package name. Maybe it could just be stripped in the `package` command itself?

2021-10-11 12:14 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
> +    val destName = fileName.stripSuffix(".sc") + "_sc.js"
Same as above, no `_sc` in the default output file name.

2021-10-11 12:14 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
> +      fileName.stripSuffix(".sc") + "_sc" + ext
Same as above, no `_sc`.

2021-10-11 12:14 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
> +    val launcherName = fileName.stripSuffix(".sc") + "_sc.jar"
Same as above, no `_sc`.

2021-10-11 12:14 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +        val output = os.proc(TestUtil.cli, extraOptions, "--native", "a.sc").call(
Maybe we should just default to `2.13` for Scala Native, and not fail that particular command…

2021-10-11 12:36 UTC, alexarchambault commented
I pushed an extra commit getting rid of the `MainClassRunner` and `_trait` stuff, that I think are unnecessary (and make scala-cli generate too many classes for single basic scripts.)

2021-10-11 12:40 UTC, tpasternak commented
Will it work for files named `main.sc`? Btw scala compiler escapes dot symbols with $002e, we would have to escape them also in main class detection code

2021-10-11 12:45 UTC, alexarchambault commented
> Will it work for files named `main.sc`?

Good point, I think adding the package name when we refer to that object from the `main` method should do.

2021-10-11 12:47 UTC, alexarchambault commented
> Btw scala compiler escapes dot symbols with $002e, we would have to escape them also in main class detection code

We can try that later, it might not be trivial overall.

2021-10-11 12:57 UTC, alexarchambault commented
> Good point, I think adding the package name when we refer to that object from the main method should do.

Quickly tried my suggestion ^, and it seems it doesn't work when we're in the root package… (but it works fine else)

2021-10-11 13:20 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/internal/CustomCodeWrapper.scala
> +                             |  def args: Seq[String] = argsOpt.getOrElse {
Let's keep `Array[String]` instead of `Seq[String]` here. We're getting a warning about the `Array` to `Seq` conversion in Scala 3 else.

2021-10-11 13:20 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/internal/CustomCodeWrapper.scala
> +                             |  def args: Seq[String] = argsOpt.getOrElse {
About the issue if the script is called `main.sc`: IMO we should just refuse to have a script named `main.sc` at the root like this. It seems we can't refer to other objects at the root with `_root_.ObjectName` (I ran into this limitation too in the `repl` command…). We could have put the scripts in a default package, but this raises a number of other issues (if we have both `.sc` and `.scala` files at the root, they can't reference each other then…)

We should also probably add some `$` signs to the other variables and methods in this object, so that they don't clash with the script name either (like `args.sc` or `argsOpt.sc`).

2021-10-11 16:24 UTC, tpasternak commented on modules/build/src/main/scala/scala/build/internal/CustomCodeWrapper.scala
> +                             |  def args: Seq[String] = argsOpt.getOrElse {
Ok, but we already have `main.sc` cases in tests and in documentation

We load this gist in one of the tests https://gist.github.com/alexarchambault/7b4ec20c4033690dd750ffd601e540ec

2021-10-11 17:14 UTC, alexarchambault commented on modules/build/src/main/scala/scala/build/internal/CustomCodeWrapper.scala
> +                             |  def args: Seq[String] = argsOpt.getOrElse {
We should change that then (I just fixed the gist).

2021-10-12 09:43 UTC, romanowski commented
It seems that @tpasternak solurion works for now and the only downside is a bit complicated but I am fine with having that in our codebase. 

As for the @alexarchambault concerns: I think we can live with so many generated classes for now.

Let's merge it for now and we can eventually fix it later.

2021-10-12 09:48 UTC, alexarchambault commented
Why did you revert my commit? The tests only needed minor changes to pass after it.

2021-10-12 10:05 UTC, alexarchambault commented
The multiple classes isn't the only problem of the `MainClassRunner` stuff. It basically creates two instances of the user variables (one in `new MainClassRunner`, one in the object extending the trait where the user code is put), which runs the entry point script twice in particular:
```text
$ cat test-proj/foo.sc
var messages = List.empty[String]
bar.init()
println("Messages:")
for (m <- messages)
  println(m)

$ cat test-proj/bar.sc
def init(): Unit =
  foo.messages = "Hello" :: foo.messages

$ ./mill -i cli.run test-proj -M foo_sc
Compiling project (Scala 3.0.2, JVM)
Compiled project (Scala 3.0.2, JVM)
Messages:
Hello
Messages:
```

2021-10-12 11:09 UTC, tpasternak commented
Ok, I reverted it because it did not support main.sc, but you're right my approach was wrong, code cannot be executed twice

2021-10-12 16:40 UTC, alexarchambault approved these changes
Looks good to me!

(I only added two NIT comments. Take them into account if you're ok with them, but it's fine merging as is, else…)

2021-10-12 16:40 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +      for { i <- Range(0, exceptionLines.length) } expect(exceptionLines(i) == expectedLines(i))
NIT, more idiomatic way of doing this:
```suggestion
      for (i <- 0 until exceptionLines.length) expect(exceptionLines(i) == expectedLines(i))
```

2021-10-12 16:40 UTC, alexarchambault commented on modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
> +      for { i <- Range(0, exceptionLines.length) } expect(exceptionLines(i) == expectedLines(i))
NIT, like above
```suggestion
      for (i <- 0 <- exceptionLines.length) expect(exceptionLines(i) == expectedLines(i))
```

2021-10-12 17:35 UTC, merged