Bloop compile to correct JVM version
VirtusLab/scala-cli pull request #217
Opened 2021-10-14 11:02 UTC by tpasternak

2021-10-15 14:00 UTC, tpasternak commented
I'd like to somehow cleaup and organize this code now. I have no idea what's the right way. 

Should I just extend `acceptBloopVersion` field function in `BloopRifleScala` in that way, it checks also bloop's jvm and restarts it if it's invalid? 

Should I download a newer jvm via couriser lib and spawn bloop with it in that case in `Operations.startServer`?

2021-10-15 14:11 UTC, alexarchambault commented
> Should I just extend acceptBloopVersion field function in BloopRifleScala in that way, it checks also bloop's jvm and restarts it if it's invalid?

Something along those lines, yes. Maybe by adding a field like `acceptJvm: Option[String => Boolean]`, that would return `true` if the passed JVM version is valid, or `false` to switch JVM (switching to using the java command provided by `BloopRifleConfig.javaPath`, so there should be no new need to initiate downloading a JVM, it's already done in `SharedOptions.bloopRifleConfig()`).

2021-10-26 14:14 UTC, tpasternak commented
Still known limitation: no way to enforce JVM 
If you set JVM 11, it is guaranteed that the bloop will be able to compile Java 11 API code, but there's no way to strictly set JVM version/path

2021-10-26 16:11 UTC, romanowski requested changes

2021-10-26 16:11 UTC, romanowski commented on modules/bloop-rifle/src/main/scala/scala/build/bloop/BloopServer.scala
> +      BloopRifle.exit(config, workdir, logger)
We need to make sure that information that bloop is restarted will be shown to user

2021-10-26 16:11 UTC, romanowski commented on modules/bloop-rifle/src/main/scala/scala/build/bloop/VersionOps.scala
> +    def toInt(s: String): Option[Int] =
```suggestion
    private def toInt(s: String): Option[Int] =
```

2021-10-26 16:11 UTC, romanowski commented on modules/bloop-rifle/src/main/scala/scala/build/bloop/VersionOps.scala
> +    def isNewerThan(rhs: String): Boolean = {
I think we should support a comparison between `1.1.1` and `1.1.2-SNAPSHOT`.  In current implementation `1.1.1` is newer

2021-10-26 16:11 UTC, romanowski commented on modules/bloop-rifle/src/main/scala/scala/build/blooprifle/BloopRifle.scala
> +    val bloopVersion = stdoutFromBloopAbout.split("\n").find(_.startsWith("bloop v")).map(
```suggestion
    val bloopVersion = stdoutFromBloopAbout.linesIterator.find(_.startsWith("bloop v")).map(
```

2021-10-26 16:11 UTC, romanowski commented on modules/bloop-rifle/src/main/scala/scala/build/blooprifle/BloopRifle.scala
>        _.split(" ")(1).trim().drop(1)
Could we add a comment with example output from bloop? Also, Woundn't `_.stripPrefix("bloop v").split(" ").head.trim` works?

2021-10-26 16:11 UTC, romanowski commented on modules/bloop-rifle/src/main/scala/scala/build/blooprifle/BloopRifle.scala
> +      .find(_.startsWith("Running on Java JDK"))
Can we migrate to regexes?

2021-10-26 16:11 UTC, romanowski commented on modules/bloop-rifle/src/main/scala/scala/build/blooprifle/BloopRifle.scala
> +    ).getOrElse(throw new RuntimeException("Could not extract bloop version"))
We should not throw exceptions when we return an option. We can consider using `Either`

2021-10-26 16:11 UTC, romanowski commented on project/deps.sc
> +  def scala3Compiler(sv: String) = ivy"org.scala-lang::scala3-compiler:$sv".exclude("*" -> "*")
Could we add a comment why we need those excludes?

2021-10-28 09:15 UTC, romanowski approved these changes

2021-10-28 12:05 UTC, merged