1.0.2 release notes
VirtusLab/scala-cli pull request #2275
Opened 2023-07-10 12:37 UTC by lwronski

2023-07-10 12:57 UTC, MaciejG604 approved these changes
LGTM!

2023-07-11 08:43 UTC, bishabosha commented on website/docs/release_notes.md
> +Added by [@zetashift](https://github.com/zetashift) in [#22029](https://github.com/VirtusLab/scala-cli/pull/22029), Thanks!
```suggestion
Added by [@zetashift](https://github.com/zetashift) in [#2202](https://github.com/VirtusLab/scala-cli/pull/2202), Thanks!
```
wrong link

2023-07-11 09:45 UTC, tgodzik requested changes

2023-07-11 09:45 UTC, tgodzik commented on website/docs/release_notes.md
> +The release also includes numerous bug fixes, updates, and new contributors.
```suggestion
This release brings enhancements to Scala CLI: 
 - WinGet installation for Windows users
 - better navigation with improved build target names 
 - introducing 'new' command for Giter8 project generation
 - easier JVM properties management with `.scalaopts` file support.
 
The release also includes numerous bug fixes, updates, and new contributors.
```

2023-07-11 09:45 UTC, tgodzik commented on website/docs/release_notes.md
> +current working directory. This simplify the JVM properties management process, eliminating the need to pass these
```suggestion
current working directory. This will simplify the JVM properties management process, eliminating the need to pass these
```

2023-07-11 09:45 UTC, tgodzik commented on website/docs/release_notes.md
> +options, such as` -Xms1024m`, will be ignored, and users will be alerted with a warning message when such non-compliant
```suggestion
options, such as` -Xms1024m`, will be ignored as they can't be used within native image, and users will be alerted with a warning message when such non-compliant
```

2023-07-11 11:18 UTC, lwronski commented on website/docs/release_notes.md
> +Added by [@zetashift](https://github.com/zetashift) in [#22029](https://github.com/VirtusLab/scala-cli/pull/22029), Thanks!
Thanks!

2023-07-11 12:52 UTC, tgodzik approved these changes

2023-07-11 13:20 UTC, merged