Doc: Tips on how to list available JVMs using coursier
VirtusLab/scala-cli pull request #3129
Opened 2024-08-26 20:40 UTC by jatcwang

2024-08-27 08:21 UTC, tgodzik requested changes
Thanks! It might useful to link to it and there is a small typo.

2024-08-27 08:21 UTC, tgodzik commented on website/docs/reference/cli-options.md
> +Use a specific JVM, such as `14`, `adopt:11`, or `graalvm:21`, or `system`. scala-cli uses **cousier** to fetch JVMs, so you can use `cs java --available` to list the available JVMs.
```suggestion
Use a specific JVM, such as `14`, `adopt:11`, or `graalvm:21`, or `system`. scala-cli uses [coursier](https://get-coursier.io/) to fetch JVMs, so you can use `cs java --available` to list the available JVMs.
```

2024-08-27 08:39 UTC, jatcwang commented on website/docs/reference/cli-options.md
> +Use a specific JVM, such as `14`, `adopt:11`, or `graalvm:21`, or `system`. scala-cli uses **cousier** to fetch JVMs, so you can use `cs java --available` to list the available JVMs.
Thanks!

2024-08-27 15:08 UTC, tgodzik commented
Could you run `./mill -i 'generate-reference-doc[]'.run` ? We have a special reference doc for SIP purposes and it needs to be up to date. Thanks!

2024-08-30 08:58 UTC, tgodzik approved these changes
Thanks!

2024-08-30 08:58 UTC, merged