Allow shading of single-choice compiler options from the command line regardless of `-`/`--` prefix
VirtusLab/scala-cli pull request #3279
Opened 2024-11-14 11:48 UTC by Gedochao

Dependencies:
- [ ] https://github.com/VirtusLab/scala-cli/pull/3253

2024-11-18 14:19 UTC, tgodzik requested changes

2024-11-18 14:19 UTC, tgodzik commented on modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
> +          k == ScalacOpt(s"-$YScriptRunnerOption") || k == ScalacOpt(s"--$YScriptRunnerOption")
```suggestion
          k.value.noDashPrefixes == YScriptRunnerOption
```
?

2024-11-18 14:19 UTC, tgodzik commented on modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
> +        "--src",
@SethTisue mentioned that we might want to actually use another name and also deprecate src and I think it makes sense. `--jar-sources` was the proposal

2024-11-18 14:19 UTC, tgodzik commented on modules/options/src/main/scala/scala/build/options/ShadowingSeq.scala
> +            case k if k.startsWith("--") => seen.contains(k) || seen.contains(k.stripPrefix("-"))
Could we stip prefixes on adding to `seen` and compare just with noDashPrefixes ?

2024-11-21 08:19 UTC, Gedochao commented on modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
> +        "--src",
I can do that in a separate PR.

2024-11-21 08:20 UTC, Gedochao commented on modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
> +          k == ScalacOpt(s"-$YScriptRunnerOption") || k == ScalacOpt(s"--$YScriptRunnerOption")
we don't care if it's `-` or `--` here.

2024-11-21 08:21 UTC, Gedochao commented on modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
> +        "--src",
a bit awkward, since we just deprecated `--source`, defaulting to `--src` 😅 
but okay.

2024-11-21 08:21 UTC, Gedochao commented on modules/options/src/main/scala/scala/build/options/ShadowingSeq.scala
> +            case k if k.startsWith("--") => seen.contains(k) || seen.contains(k.stripPrefix("-"))
Let me try that.

2024-11-21 10:37 UTC, tgodzik commented on modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
> +          k == ScalacOpt(s"-$YScriptRunnerOption") || k == ScalacOpt(s"--$YScriptRunnerOption")
I mean that's what `noDashPrefixes` is about?  it would just be a simpler code, no?

2024-11-21 16:26 UTC, Gedochao commented on modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
> +          k == ScalacOpt(s"-$YScriptRunnerOption") || k == ScalacOpt(s"--$YScriptRunnerOption")
ahh, ok. yeah, I read your first comment in a rush. lemme fix that.

2024-11-21 17:19 UTC, Gedochao commented on modules/options/src/main/scala/scala/build/options/ShadowingSeq.scala
> +            case k if k.startsWith("--") => seen.contains(k) || seen.contains(k.stripPrefix("-"))
Done

2024-11-21 17:20 UTC, Gedochao commented on modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
> +          k == ScalacOpt(s"-$YScriptRunnerOption") || k == ScalacOpt(s"--$YScriptRunnerOption")
done

2024-11-22 14:38 UTC, tgodzik approved these changes

2024-11-25 07:55 UTC, merged