Add more ScalaJs using directives
VirtusLab/scala-cli pull request #539
Opened 2022-01-11 18:49 UTC by lwronski

Add support for configure bellow ScalaJs options in using directives:

- jsHeader
- jsAllowBigIntsForLongs
- jsAvoidClasses
- jsAvoidLetsAndConsts
- jsModuleSplitStyle
- jsEsVersion

2022-01-12 15:00 UTC, romanowski requested changes
We should update JS guide as well.

2022-01-12 15:00 UTC, romanowski commented on modules/build/src/main/scala/scala/build/options/ScalaJsOptions.scala
> +      case _                 => ModuleSplitStyle.FewestModules
Shouldn't it be an error?

2022-01-12 15:00 UTC, romanowski commented on modules/build/src/main/scala/scala/build/options/ScalaJsOptions.scala
> +      case _        => ESFeatures.Defaults.esVersion
Shouldn't it be an error?

2022-01-13 19:09 UTC, lwronski commented on modules/build/src/main/scala/scala/build/options/ScalaJsOptions.scala
> +      case _                 => ModuleSplitStyle.FewestModules
Previously, we used the default version for `moduleKind`, when someone pass incorrect value. 

and now I added a warning logging, is it good enough?

2022-01-18 11:56 UTC, romanowski approved these changes

2022-01-18 11:56 UTC, merged