Emit source maps for package command
VirtusLab/scala-cli pull request #784
Opened 2022-03-16 15:53 UTC by lwronski

2022-03-17 09:00 UTC, romanowski requested changes
I think we should also add information to `--js-emit-source-map` where  source map would be created and how to change it. I think it should also have an entry on JS guide.

Beside that looks ok.

2022-03-17 09:54 UTC, alexarchambault reviewed
Don't know for @romanowski's points, but apart from the minor NIT, it's fine by me.

2022-03-17 09:54 UTC, alexarchambault commented on modules/cli/src/main/scala/scala/cli/commands/ScalaJsOptions.scala
> +      sourceMapsDest = jsSourceMapsPath.map(os.Path(_, Os.pwd)),
NIT
```suggestion
      sourceMapsDest = jsSourceMapsPath
        .filter(_.trim.nonEmpty)
        .map(os.Path(_, Os.pwd)),
```

2022-03-21 13:06 UTC, alexarchambault approved these changes

2022-03-21 13:19 UTC, merged