Package command - add support for multi modules
VirtusLab/scala-cli pull request #816
Opened 2022-03-29 10:17 UTC by lwronski

2022-03-29 11:02 UTC, alexarchambault reviewed
Apart from the minor comment, LGTM!

2022-03-29 11:02 UTC, alexarchambault commented on modules/cli/src/main/scala/scala/cli/commands/Package.scala
> +          if (os.walk(linkingDir).filterNot(_ == mainJs).filterNot(_ == sourceMapJs).nonEmpty) {
Let's use `os.walk.stream` here, that should allow not to list all files if ever there are a lot of them, or the directory contains garbage, etc.

```suggestion
          if (os.walk.stream(linkingDir).filterNot(_ == mainJs).filterNot(_ == sourceMapJs).nonEmpty) {
```
(if `geny.Generator` doesn't have a `nonEmpty` method, I guess `headOption.nonEmpty` should do…)

2022-03-29 12:20 UTC, alexarchambault approved these changes

2022-03-29 13:08 UTC, romanowski requested changes
Shouldn't we update js documentation?

2022-03-29 13:09 UTC, armanbilge commented
This feature is already mentioned in the documentation, it just wasn't working :)

https://scala-cli.virtuslab.org/docs/reference/cli-options/#--js-module-split-style

2022-03-29 13:24 UTC, lwronski commented
> Shouldn't we update js documentation?

I think, that I confusingly named PR, it is more bug fixes. Because if someone run `package --js` command with the following scala file:
```
  @JSExportTopLevel(name = "onRequest", moduleID = "request_type")
  def func(...)

  @JSExportTopLevel(name = "onRequest", moduleID = "request_headers")
  def func(...)
```
he gets an error that `main class is missing`, when run generated js file. This PR fixed it.

2022-03-30 11:35 UTC, romanowski commented
That is valid, however current Scala JS guide does not have a section about publishing so I think we should describe the publishing for JS. We have a [small section ](https://scala-cli.virtuslab.org/docs/guides/scala-js)at `publish` command but I think it only covers a basic scenario.

So I am merging this PR for now, @lwronski could you review the documentation for packaging in JS and create a follow up PR if needed?

2022-03-30 11:35 UTC, merged

2022-03-30 12:23 UTC, armanbilge commented
Note that publishing (i.e., uploading SJSIR files to Maven) is different from packaging (linking SJSIR files into JS files).